[project]
name = "event-driven-agentic-workflows"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.49.1",
    "jupyter>=1.1.1",
    "llama-index-core>=0.14.5",
    "llama-index-embeddings-openai>=0.5.1",
    "llama-index-llms-openai>=0.6.5",
    "llama-index-readers-whisper>=0.2.1",
    "llama-index-utils-workflow>=0.4.1",
    "llama-parse>=0.6.76",
]
